#!/bin/bash

volume() {
    vol=$(pulsemixer --get-volume | cut -d " " -f1);
    if [ $(pulsemixer --get-mute) == 1 ];
    then
      printf "MUTE%3d%%" $vol
    else
      printf "VOL %3d%%" $vol
    fi
}

case $BLOCK_BUTTON in
  3) pulsemixer --toggle-mute ;;      # right click, mute/unmute
  4) pulsemixer --change-volume +5 ;; # scroll up, increase
  5) pulsemixer --change-volume -5 ;; # scroll down, decrease
esac

volume
